[windows]
winhost ansible_host=10.0.1.120

[windows:vars]
ansible_user=Administrator
ansible_password=3-p!B.S8.2Ers?Jv&wzwv%&M1FOieHpU
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985%
