[linux]
linuxhost ansible_host=10.0.1.120 ansible_port=22

[linux:vars]
ansible_user=your_linux_user
ansible_password=your_linux_password
ansible_connection=ssh
ansible_become=yes
ansible_become_method=sudo
ansible_ssh_common_args='-o StrictHostKeyChecking=no'