---
- name: Test Windows connectivity
  hosts: windows
  gather_facts: no

  tasks:
    - name: Ping Windows host
      ansible.windows.win_ping:

    - name: Get hostname
      ansible.windows.win_shell: hostname
      register: hostname_output

    - name: Show hostname
      ansible.builtin.debug:
        var: hostname_output.stdout
